#!/usr/bin/env python3
"""Generate docs/adr/ACTIVE.md from ADR frontmatter."""

from __future__ import annotations

import argparse
import pathlib
import re
import subprocess
import sys
from typing import Any

try:
    import yaml
except ImportError:
    sys.exit("error: PyYAML not installed. Run: pdm install -G tests")


STATUS_ORDER = ["Proposed", "Accepted", "In Progress", "Implemented", "Superseded"]
STATUS_HEADINGS = {
    "Proposed": "## Proposed",
    "Accepted": "## Accepted",
    "In Progress": "## In Progress",
    "Implemented": "## Implemented",
    "Superseded": "## Superseded",
}
FRONTMATTER_RE = re.compile(r"\A---\n(.*?)\n---", re.DOTALL)


def repo_root() -> pathlib.Path:
    try:
        out = subprocess.check_output(
            ["git", "rev-parse", "--show-toplevel"],
            stderr=subprocess.DEVNULL,
            text=True,
        ).strip()
        return pathlib.Path(out)
    except (subprocess.CalledProcessError, FileNotFoundError):
        return pathlib.Path.cwd()


def adr_dir(root: pathlib.Path) -> pathlib.Path:
    candidate = root / "docs" / "adr"
    if candidate.is_dir():
        return candidate
    sys.exit(f"error: no docs/adr directory under {root}")


def parse_frontmatter(path: pathlib.Path) -> dict[str, Any] | None:
    text = path.read_text(encoding="utf-8")
    match = FRONTMATTER_RE.match(text)
    if not match:
        return None
    try:
        data = yaml.safe_load(match.group(1))
    except yaml.YAMLError:
        return None
    return data if isinstance(data, dict) else None


def iter_adr_files(directory: pathlib.Path):
    for file in sorted(directory.glob("[0-9]*-*.md")):
        if file.is_file():
            yield file
    for subdir in sorted(directory.glob("[0-9]*-*")):
        readme = subdir / "README.md"
        if subdir.is_dir() and readme.is_file():
            yield readme


def render(buckets: dict[str, list[dict[str, Any]]]) -> str:
    lines = [
        "# ADR Kanban",
        "",
        "> Generated by `scripts/adr-index.py` from ADR frontmatter. Do not edit manually.",
        ">",
        "> Lifecycle: Proposed -> Accepted -> In Progress -> Implemented / Superseded",
        "",
    ]
    for status in STATUS_ORDER:
        lines.append("---")
        lines.append("")
        lines.append(STATUS_HEADINGS[status])
        lines.append("")
        lines.append("| ADR | Author | Date | Summary |")
        lines.append("|-----|--------|------|---------|")
        rows = sorted(
            buckets.get(status, []),
            key=lambda row: str(row.get("date", "")),
            reverse=True,
        )
        for row in rows:
            lines.append(
                "| [{id}]({path}) | {author} | {date} | {summary} |".format(
                    id=row.get("id", "?"),
                    path=row["relpath"],
                    author=row.get("author", ""),
                    date=row.get("date", ""),
                    summary=row.get("summary", ""),
                )
            )
        lines.append("")
    return "\n".join(lines).rstrip()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="overwrite ACTIVE.md")
    args = parser.parse_args()

    root = repo_root()
    directory = adr_dir(root)

    buckets: dict[str, list[dict[str, Any]]] = {status: [] for status in STATUS_ORDER}
    for path in iter_adr_files(directory):
        fm = parse_frontmatter(path)
        if fm is None:
            continue
        status = str(fm.get("status", "")).strip()
        if status not in buckets:
            continue
        relpath = "./" + str(path.relative_to(directory)).replace("\\", "/")
        buckets[status].append(
            {
                "id": fm.get("id", ""),
                "author": fm.get("author", ""),
                "date": fm.get("date", ""),
                "summary": fm.get("summary") or "",
                "relpath": relpath,
            }
        )

    output = render(buckets)
    if args.write:
        (directory / "ACTIVE.md").write_text(output + "\n", encoding="utf-8")
        print(f"wrote {directory / 'ACTIVE.md'}")
    else:
        print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
